version: '3'

services: 
  app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

      - KAFKA_HOST=localhost
      - KAFKA_PORT=9092
    links:
      - rabbitmq
      
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672"
      - "15672:15672"